server:
  port: 8888

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mist_cloud_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
  sql: # 总是执行初始化脚本
    init:
      mode: never
      continue-on-error: false # 执行sql出错就终止
      platform: mysql
      schema-locations: classpath:db/schema/mist_cloud_schema.sql
      data-locations: classpath:db/data/mist_cloud_data.sql
  mail:
    host: smtp.qq.com
    port: 465
    username: gongjiatian00@qq.com
    # 使用 jasypt 加密密码，使用com.xkcoding.email.PasswordTest.testGeneratePassword 生成加密密码，替换 ENC(加密密码)
    password: sfnknboxmnkvdfff
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: spring-boot-demo
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
# 为 jasypt 配置解密秘钥
jasypt:
  encryptor:
    password: mist-cloud



# swagger地址
# localhost:8888/swagger-ui/index.html#/

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.mist.cloud.infrastructure.entity
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


logging:
  level:
    com.mist.cloud.infrastructure.mapper: DEBUG

file:
  base_path: /Users/securemist/Downloads/mist-cloud

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-64
  # 是否输出操作日志
  is-log: false
#  log-level: DEBUG







