spring:
  profiles:
    active: dev

  mail:
    host: smtp.qq.com
    port: 465
    username: gongjiatian00@qq.com
    password: sfnknboxmnkvdfff
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: spring-boot-demo
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB

# springdoc-openapi项目配置
# 文档地址 http://localhost:8888/swagger-ui/index.html#/
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mist.cloud
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.mist.cloud.infrastructure
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.mist.cloud.infrastructure.mapper: DEBUG

sa-token:
  token-name: satoken
  timeout: 2592000
  is-concurrent: true
  is-share: true
  token-style: random-64
  is-log: false




